# Server
server:
  port: 8090

# Spring
spring:
  application:
    name: api-gateway

# Security
security:
  oauth2:
    client:
      client-id: auth_id
      client-secret: auth_secret
    resource:
      jwt:
        key-value: jwt_secret_key

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Zuul
zuul:
  routes:
    user-service:
      path: /api/user/**
  sensitive-headers: Cookie,Set-Cookie
  add-proxy-headers: true



