# Server
server:
  port: 8005

# Spring
spring:
  application:
    name: msa-keyword-service
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Security
security:
  oauth2:
    client:
      client-id: auth_id
      client-secret: auth_secret
    resource:
      jwt:
        key-value: jwt_secret_key

# Elasticsearch
elasticsearch:
  host: ec2-18-221-151-100.us-east-2.compute.amazonaws.com
  port: 9200